baseURL: "https://arkalim.org"    #netliffy free sub domain
languageCode: en-us
title: Vipin Chandran Muthirikkaparambil
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: Certifications
      name: Certifications
      url: /Certifications
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Vipin Chandran Muthirikkaparambil"
    subtitle: Hello! I'm Vipin, currently pursuing my [**Masters of Engineering (M.Eng) in Systems and Technology with specialization in Automation and Smart Systems**](https://www.eng.mcmaster.ca/sept/programs/degree-options/meng-st-systems-technology/#tab-content-automation-smart-systems) at the esteemed **McMaster University**, Hamilton, ON, Canada. I bring a solid foundation in Software Engineering with couple of years of industrial professional experience. To enhance my expertise, I have also obtained AWS associate-level certifications as a Solutions Architect and Developer, further bolstering my skills in the cloud computing domain. My unwavering curiosity and drive push me to explore fresh avenues to redefine technological frontiers. 
    imageUrl: "home/vipin.jpg"
    imageWidth: 320
    imageHeight: 410
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:vipinchandranm24@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/mvipinchand"
    - name: "github"
      url: "https://github.com/mvipinchand"
    - name: "cv"
      url: "https://docs.google.com/document/d/1CaoNeV9-8Fd_fAc2OVlqjbjLnQ5CQbYY5XJCTlldN70/edit"   ##Make it view only PDF

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
